### ISSUE TITLE
Undefined reference in atcmd_wifi.c when using "CONFIG_EXAMPLE_UART_ATCMD 1"

### ISSUE THREAD

**Issue by noah00kr** [ambiot/ambz2_sdk#29]
Hello!!!
If building after setting "CONFIG_EXAMPLE_UART_ATCMD 1", "undefined reference" happens as the following.
Please check this.

![image](https://user-images.githubusercontent.com/33437834/172531993-fe4fe2b0-b05b-4b69-870b-0134ed92e34c.png)

**Comment by Wuth5** [comment]
Dear noah,
currently github version do not support at cmd version2

**Comment by noah00kr** [comment]
Dear wu tanghong,
Thank you for your kind explanation.
