### ISSUE TITLE
How to build bluetooth example app with auto PROVISION mesh device?

### ISSUE THREAD

**Issue by git-hub-cloud** [ambiot/ambz2_sdk#39]
Many devices boot up with default app/net key etc. NOT need phone app or AT command to config. Example mesh app: component/common/bluetooth/realtek/sdk/example/bt_mesh_device_rtk_demo/

**Comment by Wuth5** [comment]
hi @jiqianghu, thanks for your interest in the project. For now, we do not support this feature in the public code repository.

**Comment by jiqianghu** [comment]
I mean that devices can simulate to be provisioned, so these devices can communiate when power on with the same net/app key etc. 
How can I update the device SDK? Can you give me some suggestions?

**Comment by git-hub-cloud** [comment]
@Wuth5 I mean that devices can simulate to be provisioned, so these devices can communiate when power on with the same net/app key etc. 
How can I update the device SDK? Can you give me some suggestions?

**Comment by Wuth5** [comment]
Hi @jiqianghu, yes I understand, and if you want to build SDK with this feature you may consider our NDA SDK, can contact our sales for more info. For github version it is not supported.

**Comment by jiqianghu** [comment]
@Wuth5 I don't know NDA SDK :) . My SDK is from MI, and they don't want to support mesh at the SDK/SOC. I want to give user more powerful function with local mesh.

**Comment by git-hub-cloud** [comment]
> hi @jiqianghu, thanks for your interest in the project. For now, we do not support this feature in the public code repository.

@Wuth5 Do you mean NDA sdk to support auto provision? I compile NDA mesh demo device with many errors(no .c/.h files), but the public code is ok. So can I build auto mesh device with the public code?

**Comment by Wuth5** [comment]
Hi @jiqianghu , sry for the late reply. Regarding to the NDA sdk it is not suitable to discuss in github, you can  contact our customer supports for official support about this issue, here is the list of customer service you may consider https://www.realtek.com/zh-tw/contact-us/cu-1-tw/cu-1-taiwan-tw
appreciate for your understanding
you may attach the SDK version (in readme.txt you can find latest patch version) and compile error logs when you contact them

**Comment by git-hub-cloud** [comment]
thank you.
