### ISSUE TITLE
mesh features relay not enable?

### ISSUE THREAD

**Issue by git-hub-cloud** [ambiot/ambz2_sdk#40]
Set .relay=1 at a device. nRF Mesh Android app acts as provisioner, it shows "Disabled". How to enable relay feature? 
![无标题](https://github.com/ambiot/ambz2_sdk/assets/6647429/aac54b66-823c-405b-b706-69bdd9afd906)

**Comment by Wuth5** [comment]
Hi @jiqianghu,
all the available bt features are listed in platform_opts_bt.h, set the struct value will take no effect as the corresponding feature will not be compiled
