### ISSUE TITLE
Inquiry about the “Boot Partition Table Header Verification Error” issue

### ISSUE THREAD

**Issue by cw-20021349** [ambiot/ambz2_sdk#45]
Hello,

I have purchased the AMEBA Z2 AWS IOT EXPRESSLINK DEV development board.

Additionally, I’ve set up the Ubuntu build environment and built the sample source code. After building, I downloaded the generated flash_ls.bin file using the AmebaZ2_PGTool. https://github.com/ambiot/ambz2_sdk/blob/amazon/readme_for_support_Amazon_v202012-LTS_v02.txt

![스크린샷 2023-08-30 오후 5 07 11](https://github.com/ambiot/ambz2_sdk/assets/98305286/8d3ff1f4-f9de-4dc4-aeba-f0a225f341cc)

After completing the download, I encounter the following error log during boot:

== Rtl8710c IoT Platform ==
Chip VID: 5, Ver: 3
ROM Version: v3.0
[BOOT Err]Parttiton Table Header Verification Err!
StartUp@0x0: Invalid RAM Img Signature!

I would appreciate it if you could provide a guide to resolve this situation.

Thank you for your assistance. 
Best regards.

**Comment by ZHI-ANG** [comment]
Hi, did you solve this issue? Would you mind sharing how you solved it? Thanks!
